import Head from 'next/head';
import React, { ReactChild } from 'react';

interface IPageWrapperProps {
	children: ReactChild;
	title?: string;
	meteName?: string;
	metaContent?: string;
}

const MainPageLayout: React.FC<IPageWrapperProps> = ({
	title = 'Nextjs app ',
	children,
	meteName = 'description',
	metaContent = 'Generated by create next app',
}) => {
	return (
		<>
			<Head>
				<title>{title}</title>
				<meta name={meteName} content={metaContent} />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			{children}
		</>
	);
};

export default React.memo(MainPageLayout);
